# Generated by Django 4.1 on 2022-09-19 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('i_shop', '0004_order_delivery_type_order_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='total_to_pay',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
